services:
  - type: web
    name: bank-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bank_database
          property: connectionString
      - key: JWT_SECRET
        generateValue: true